version: '3.6'
services:
  db:
    image: mariadb:10.6.4
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
    volumes:
    - db-persist:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: wp
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: wordpress
  db_pma:
    image: phpmyadmin:latest
    depends_on:
    - db
    ports:
      - 8080:80
    environment:
      PMA_USER: wp
      PMA_PASSWORD: password
  wp:
    build:
      context: ./docker
      dockerfile: WordPress.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
    - ./www/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: password
  gb:
    build:
      context: ./docker
      dockerfile: Gatsby.Dockerfile
    depends_on:
      wp:
        condition: service_started
    #command: gatsby develop -H 0.0.0.0 -p 3000
    volumes:
    - ./www/gatsby:/app
    ports:
    - 9000:9000
  proxy:
    image: nginx:mainline-alpine
    depends_on:
     - wp
     - gb
    volumes:
     - "./nginx:/etc/nginx/conf.d"
    ports:
     - 80:80
     - 443:443
volumes:
    db-persist:
